### ISSUE TITLE
reduce scope of HK2 dependency

### ISSUE THREAD

**Issue by hankipanky** [darmbrust/HK2Utilities#1]
I'd like to suggest that the scope of the dependency on HK2 is reduced to `provided` to avoid the library-specific version of HK2 making it into the final application.

Whoever is interested in this library is already using HK2 and quite possibly wants to have control over the version that is included in the application. Specifying a direct, transitive dependency on HK2 in the HK2Utilities library works against that goal. 

I have stumbled across this, since I have recently updated my deps, and HK2 is now in use in version 2.6.1. However, hk2-2.5.0-b61 still appeared in my classpath/fat jar.

**Comment by darmbrust** [comment]
Its not a bad idea... though I'm surprised maven wouldn't have figured out that you had an older and newer dependency listed, and used the newer one.  You can always put an exclusion on HK2 where you depend on the HK2 Utilities.

I obviously haven't updated this in a while... I'll try to get a release done here in the next couple of weeks... I believe if I just mark it provided, it won't work for the included tests... I'll take a look.

**Comment by hankipanky** [comment]
My problem is with packaging everything into a fat jar, where the shade-plugin complains about multiple versions. Also, from a conceptual point of view, I find it more logical for the application which is based on HK2 to specify the version-at-runtime, not a utility library.

Scope 'provided' works fine for tests. See [maven.apache.org](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope):

> provided: [...] This scope is only available on the compilation and test classpath, and is not transitive.

Alternatively checkout the PR.

**Comment by darmbrust** [comment]
this is resolved in the 1.6.0 release
